catch_rules: #转换规则
    - rule: _ 
      transform_rules: 
        - search: \#.* 
          replace: ''
        - search: _ 
          replace: 
          - _ #保留原始请求
          - 76log.vercel.app
          - unpkg.com/wblog
          - cfb.wmza.cn
          - cdn.cbd.int/wblog

        - search: ([^\/.]+)\/$
          replace: $1/index.html

        - search: \.html$
          header:
            Content-Type: text/html;charset=UTF-8 #修复标头

        - search: _
          action: fetch
          fetch:
            status: 200
            engine: Parallel
            preflight: false
            timeout: 5000
